### ISSUE TITLE
App's icon is black instead of cyan on Windows 11 taskbar

### ISSUE THREAD

**Issue by shuyuan-liu** [tomcl/issie#111]
This problem was noticed shortly after downloading the v2.2.9 release. On my Windows 11 system using a dark taskbar, the Issie icon is black making it nearly impossible to see:

![image](https://user-images.githubusercontent.com/41851763/139400221-56c4d898-6a30-4f55-82e9-4de4da6c4bce.png)

Changing the system's colour mode to Light gives better contrast but the icon is still black:

![image](https://user-images.githubusercontent.com/41851763/139400856-40299053-edef-434a-8e40-cbc3fc8b4e8c.png)

In Windows Explorer, issie.exe has a cyan-coloured icon; the icon on Issie's title bar is black.

On Windows 10, the icon in the taskbar is the same as that of issie.exe, both cyan, and only the icon in Issie's title bar is black.

**Comment by tomcl** [comment]
Thanks for this. I can see that is annoying. It is the type of OS-dependent thing that will either be trivial or difficult to mend. i will have a look to see what can be done for the next bugfix release.

**Comment by tomcl** [comment]
Closed in [v2.3.0](https://github.com/tomcl/issie/releases/tag/v2.3.0)
