### ISSUE TITLE
Cosmetic: App's icon has an opaque white background

### ISSUE THREAD

**Issue by shuyuan-liu** [tomcl/issie#116]
issie.exe's icon has an opaque white background whereas most other file and folder icons in Windows do not. This makes the icon look slightly out of place when highlighted in Explorer as well as in the Start menu. Since [v2.3.0](https://github.com/tomcl/issie/releases/tag/v2.3.0) this also affects the icon in the taskbar.

![image](https://user-images.githubusercontent.com/41851763/141791424-67c0abb5-0b5e-4279-a826-a0ffd01ac3d3.png)

![image](https://user-images.githubusercontent.com/41851763/141791657-b4fe7840-e294-41a7-9151-f07cdc4be79c.png)

![image](https://user-images.githubusercontent.com/41851763/141791504-8e2b1aba-2e9c-4b6c-b617-9bc5adcfe899.png)

**Comment by tomcl** [comment]
:)

I don't have a clue about this windows icon stuff. I guess I need a png file with a transparent background. I will leave this open till somone (maybe me) feels inspired to deal with it. The png is: `/static/icon-1.png`.

**Comment by tomcl** [comment]
I've turned this into an png with a transparent background. It still does not work. I may be missing something, e.g. the tray icon comes from somewhere weird in the build I'm not seeing

I'll keep this open but it is tricky to address and very low priority.

**Comment by tomcl** [comment]
It is totally mysterious when this background is transparent and when not. I think I have fixed it v2.3.3 - but maybe not in shortcuts to old executables etc.
