### ISSUE TITLE
Use a diffirent default folder for New Project

### ISSUE THREAD

**Issue by shuyuan-liu** [tomcl/issie#118]
When creating a project for the first time in ISSIE v2.3.2 on Windows 11, it navigates to the folder `C:\Windows\System32`, which is not (and probably shouldn't be) where most people store their circuit diagrams. A more reasonable default could be the user's Documents folder. This isn't a big issue however as it only happens the first time.

**Comment by tomcl** [comment]
Fixed v2.3.3
