### ISSUE TITLE
Show tooltip with description when hovering components in the catalogue.

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#12]
<a href="https://github.com/ms8817"><img src="https://avatars2.githubusercontent.com/u/61198467?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ms8817](https://github.com/ms8817)**
_Friday Jun 19, 2020 at 14:18 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/45_

----

Maybe also show the keyboard shortcuts when hovering buttons like `save`, `copy` and `paste`?

**Comment by tomcl** [comment]
Done!
