### ISSUE TITLE
Minor graphical enhancement: Add clock input to sequential user block

### ISSUE THREAD

**Issue by edstott** [tomcl/issie#124]
Consistency and legibility could be slightly improved by adding a clock input to the symbols for user-defined blocks that contain sequential logic. Like the clock on built-in blocks, the clock input would only be graphical and not connectable.

**Comment by tomcl** [comment]
Great idea. I will add it to the HLP work in Spring Term

**Comment by tomcl** [comment]
done v3.0.0
