### ISSUE TITLE
Directly using ISSIE on network location (H:)

### ISSUE THREAD

**Issue by ChangLiu2022** [tomcl/issie#125]
ISSIE 2.4.0 isn't functioning running directly from the H: drive using college computer. It behaves as follows and quits a while later.
![1](https://user-images.githubusercontent.com/98478845/151208232-8e72c9e7-4ef7-4ad1-b9a6-f978b9e2fdfb.png)

**Comment by tomcl** [comment]
Yes, that is correct. It is to do with networked PC  (I think).

**Workaround**

open command window, navigate to the top-level issie binary directory that contains issie.exe

run:

issie.exe --no-sandbox

**Comment by ChangLiu2022** [comment]
> Yes, that is correct. It is to do with networked file system on PC (I think).
> 
> **Workaround**
> 
> open command window, navigate to the top-level issie binary directory that contains issie.exe
> 
> run:
> 
> ```
> issie.exe --no-sandbox
> ```
> 
> let me know if that works - it does work on a networked path on my PC.

It works! Thank you for sharing this. 

Find it easier to set up a shortcut with the ' --no-sandbox' at the end of 'Target:' line in its properties, so I don't need to type command every time I use issie. :)
