### ISSUE TITLE
Changing mouse icons.

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#13]
<a href="https://github.com/ms8817"><img src="https://avatars2.githubusercontent.com/u/61198467?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ms8817](https://github.com/ms8817)**
_Friday Jun 19, 2020 at 14:21 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/46_

----

When hovering a component there should be a mouse drag icon.
When hovering a connection endpoint there should be something specific to creating connections (maybe a wire icon or something like that).

**Comment by tomcl** [comment]
fixed v3.0.0 (mostly before)
