### ISSUE TITLE
Copy and Paste within Memory Editor affects sheet

### ISSUE THREAD

**Issue by luigirinaldi** [tomcl/issie#134]
When copying and pasting values into the memory editor, any component previously saved in the clipboard also gets pasted in the underlying sheet.

Issie v2.4.0 running on Windows 11

**Comment by tomcl** [comment]
upgrade to latest (v2.4.4)! That issue was closed a while ago.

**Comment by tomcl** [comment]
PS - let me know if that fix does not deal with the problem?

**Comment by luigirinaldi** [comment]
Thank you very much. The new version has fixed the issue.
