### ISSUE TITLE
Standard wire intersection notation?

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#14]
<a href="https://github.com/ms8817"><img src="https://avatars2.githubusercontent.com/u/61198467?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ms8817](https://github.com/ms8817)**
_Friday Jun 19, 2020 at 14:28 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/47_

----

At the moment the applications uses:
- wires that are crossing but not touching: straight lines.
![image](https://user-images.githubusercontent.com/61198467/85142869-43ea3280-b249-11ea-93f1-cf78a3c1f2b5.png)
- branches: curved lines.
![image](https://user-images.githubusercontent.com/61198467/85142942-5d8b7a00-b249-11ea-953e-9468b06c9141.png)

One may consider moving the standard notation with a dot instead.
Draw2d actually offers a connections router that has this capability (`CircuitConnectionRouter`) but it is not interactive (wires cannot be manually moved). One could write their own `InteractiveCircuitConnectionRouter`.

**Comment by tomcl** [comment]
We lost curved lines with the new F# draw block. So we have now only one method out of 3!

**Comment by tomcl** [comment]
fixed v3.0.0
