### ISSUE TITLE
Wires do not correctly attach to input ports on components when reopening file from older ISSIE version

### ISSUE THREAD

**Issue by blayney** [tomcl/issie#146]
V2.5.0, Windows 10

![image](https://user-images.githubusercontent.com/34400052/162545061-be070f39-6593-4355-93d2-ae2c1f0f8a97.png)

You can see in this screenshot that the wire previously connected to ALUF is now floating - the only workaround appears to be moving the end target of the wire (ALUF) which resyncs the end position of the wire. On big sheets opened for the first time on 2.5.0 this means moving every single component with missing input wires, which can be lots!
There's another missing input wire on a merge towards the top right. This issue persists across styling, and I'm not certain it only occurs on 2.5.0. If helpful, I can find the ISSIE version the files were created on. Thanks!

**Comment by tomcl** [comment]
I will fold a fix for this into the next alpha release (soon).

**Comment by tomcl** [comment]
OK - it looks like this was mended around 2.5.0a2 or so.

Download the latest 2.5.0a binary (we are now on a8). It will have bugs mended and extra features.

There will be proper releases when we are out of the alpha testing stage - till then you have to check for the publish date of release tags (they all have the same Issie version).

Let me know if this does not resolve the problem!
