### ISSUE TITLE
Add labelled connectors.

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#15]
<a href="https://github.com/tomcl"><img src="https://avatars0.githubusercontent.com/u/7545073?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomcl](https://github.com/tomcl)**
_Friday Jun 19, 2020 at 18:59 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/50_

----

Like an input or output connector, but colored differently (?) and represents connections within one sheet where all same labelled connectors are one net. Arguably you could have connector i/o tabs but I quite like explicitly knowing whether the signal is going out of coming into each label in a labelled net.

labelled inputs with special labels '0', '1' or (enhancecement) labelled busses iwth "0x34" could be used to provide constants, thus dealing with  #35

**Comment by tomcl** [comment]
Done (over the Summer) and available as Label connector. In retrospect the labels used, which have input and output connections, are probably over-complex. Better to have just label drivers and labels which are driven (one per net). Anyway it is now done.
