### ISSUE TITLE
Dividerbar for WaveSim tab does not span the whole height when the right-tab section becomes scrollable

### ISSUE THREAD

**Issue by adidesh20** [tomcl/issie#170]
**Describe the bug**
The right tab section for the Waveform Simulator is set to become scrollable when it overflows (i.e. there are a large number of possible waves). When scrolling down the list, the height of draggable dividerbar does not extend, instead staying at the original height of the section

**To Reproduce**
1. Open a sheet with a large number of sequential components (I used eep1 from lab5eep1model)
2. Click on the Waveforms button
3. Scroll down the list of waveform checkboxes
4. See how the the height of the dividerbar does not change

**Expected behavior**
The dividerbar should extend as the user scrolls

**Screenshots**
<img width="1435" alt="Screenshot 2022-05-25 at 17 13 13" src="https://user-images.githubusercontent.com/50241177/170310613-079343bb-9116-478b-b5f2-c272bd4dc398.png">

**Additional notes**
Discovered this issue on my fork, where long truth tables cause the same problem.

**Comment by adidesh20** [comment]
Have now opened a PR that fixes this issue

**Comment by jzzheng22** [comment]
#171  is not a perfect solution: the very first time it is loaded, the divider bar is still the wrong height. Any time after that it is fine.

I'm not really sure what the best way of resolving this is. Could perhaps force a reload if it is the first time the bar is loaded, but that would require mutable state I think? Maybe not worth it.
