### ISSUE TITLE
Improve dev envt bootstrap

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#18]
<a href="https://github.com/tomcl"><img src="https://avatars0.githubusercontent.com/u/7545073?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomcl](https://github.com/tomcl)**
_Friday Jun 19, 2020 at 22:10 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/56_

----

The windows setup,bat file should run paket.bootstrapper.exe (from .paket directory). This will install paket and remove one manual install step.

Something similar for the linux / macos  setup.sh script.

refrence: https://fsprojects.github.io/Paket/installation.html

**Comment by tomcl** [comment]
We have now switched (> v1.0.8) to Fable 3.0.0, and in the process much simplified the dev envt and improved its cross-platform rannability.
