### ISSUE TITLE
Improve electron-specific boilerplate

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#19]
<a href="https://github.com/tomcl"><img src="https://avatars0.githubusercontent.com/u/7545073?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomcl](https://github.com/tomcl)**
_Friday Jun 19, 2020 at 22:51 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/57_

----

catching events in electron main process will make any electron app nicer. Specifically:

display a solid color in window during startup, do not display anything till ready-to-show is emitted
https://www.christianengvall.se/electron-white-screen-app-startup/

catch window cancel and if there is unsaved data query whether this is wanted.
https://stackoverflow.com/questions/48408014/electron-catch-when-window-is-closed-using-the-x-button

(Visual2 has some examples of this using javascript / F#)

**Comment by tomcl** [comment]
done v3.0.0 (in fact earlier than this as well).
