### ISSUE TITLE
Not all IOLabel components and connections are highlighted when hovered over in the waveform simulator

### ISSUE THREAD

**Issue by jzzheng22** [tomcl/issie#190]
**Describe the bug**
Created by #189.

When hovering over a wire label in the waveform simulator, only one IOLabel and connection is highlighted, rather than all IOLabels with the same name (and corresponding connections).
This is as a result of how wire labels are generated:

- In the function `getWaves`, the `List.distinctBy` method is called to remove duplicate IOLabels. This is so that only one IOLabel actually appears in the waveform selection pane.
- There can be multiple IOLabels, each with a different `ComponentId`, but the same `Label`.
- Only one of these IOLabels with the same `Label` appears in the `WaveSimModel`, and therefore only that IOLabel will be highlighted.
- It is not trivial to solve this nicely (you could do it somewhat easily but the code would have lots of technical debt): you would need some way of embedding both the `ComponentIds` as well as the `SourceConnId`s and `TargetConnId`s of each of the duplicate IOLabels in the `Wave` type.
- This requires changing the `Wave` type: you would presumably add an optional field that contains the extra `ComponentId`s that has a `None` value for other component types and any IOLabels of which there is only one instance.
- The above changes would also probably require some tweaks to how waves are named.

What is (maybe) a relatively easy way of fixing this with the current implementation is:

1. Generate all waves without removing duplicate IOLabels
2. After all IOLabel waves are generated, go through the IOLabels and group them by component label.
3. For each group, take one IOLabel (I don't think it matters). For all other IOLabels, take their `Conns` and `ComponentId` fields and add them to the first IOLabel. For the `ComponentId`s, these should be added to a new optional field in the `Wave` type.

    - It might matter which one you pick: probably pick one where the index PortType is not an Input: this will maybe make it easier?
    - But that's also irrelevant: `makeWave` fails for IOLabels that are an InputPort type. Specifically, it fails in the `Some None` case:
   
```
match Map.tryFind (InputPortNumber index.PortNumber) comp.Inputs with
| Some (Some nlSource) -> netList[nlSource.SourceCompId], nlSource.OutputPort
| Some None -> failwithf "is there an unconnected input?\n wave: %A\n port: %A %A\n type: %A" comp.Label index.PortType index.PortNumber comp.Type
| None -> failwithf "InputPortNumber %A not in comp.Inputs" (index.PortNumber)
```

5. When highlighting IOLabel components, dispatch a message including this id list.

**Comment by tomcl** [comment]
For fix late Summer 2022

**Comment by tomcl** [comment]
closed over wave sim integration period.
