### ISSUE TITLE
Nicer way to attack keyboard shortcuts?

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#22]
<a href="https://github.com/ms8817"><img src="https://avatars2.githubusercontent.com/u/61198467?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ms8817](https://github.com/ms8817)**
_Saturday Jun 20, 2020 at 14:55 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/61_

----

There may exist a better way to attach keyboard shortcuts, different from the current version.
Check this:
http://www.lib4dev.in/info/fable-compiler/fable-electron/185369621

I initially experimented with globalShortcut but it seemed to capture key combinations also from other Electron windows (such as VSCode).

**Comment by tomcl** [comment]
closed - not needed.
