### ISSUE TITLE
Can’t simulate counter in step or wave mode when ‘LOAD’ input is derived from ‘Q’ output

### ISSUE THREAD

**Issue by edstott** [tomcl/issie#220]
**Describe the bug**
Simulation commands are unresponsive when the design contains a counter with load, and the load signal is derived from the output of the counter. Simulation works correctly when load is driven by an input port. 

**To Reproduce**
1. Load attached design
[test.zip](https://github.com/tomcl/issie/files/9581967/test.zip)
2. Open Step Simulation tab
3. Click Start Simulation
4. Click 'Clock Tick 0'
5. At this point, further clicks of 'Clock Tick' and 'Goto Tick' have no effect. Wave simulation is similarly unresponsive

**Expected behavior**
Simulation should continue

**Desktop:**
 - OS: e.g. Windows 10
 - Version 3.0.0 built from https://github.com/tomcl/issie/commit/a83cc21920e497ee8b5c7527d268383ce3ed9827

**Comment by apantelopoulos** [comment]
@edstott  Do you mean a design like this? Or something else?

![image](https://user-images.githubusercontent.com/59971511/190639453-8d5e3bf0-547f-422c-bcd7-8741f16e4399.png)

**Comment by edstott** [comment]
Like this:
![image](https://user-images.githubusercontent.com/4660308/190641224-a95b2ea2-acfe-4adc-a26f-efaa613fc90b.png)

**Comment by edstott** [comment]
This is what you'd if you wanted a counter period that wasn't 2^n

**Comment by apantelopoulos** [comment]
Fixed on #232
