### ISSUE TITLE
Crash when deleting input port while simulation is active

### ISSUE THREAD

**Issue by edstott** [tomcl/issie#221]
**Describe the bug**
The software becomes unresponsive with a blank window when you delete an input port during a simulation

**To Reproduce**
1. Open attached 
[test2.zip](https://github.com/tomcl/issie/files/9582028/test2.zip)
2. Open Step Simulation tab
3. Click 'Start Simulation'
4. Delete the 'IN' component

**Expected behavior**
Sheet should be editable while simulation is active, albeit without edits affecting the current simulation

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.0 built from https://github.com/tomcl/issie/commit/a83cc21920e497ee8b5c7527d268383ce3ed9827

**Comment by tomcl** [comment]
Closed by https://github.com/tomcl/issie/commit/b7331a66134d0e3a5e79c044efad8ca45c1dbf43
