### ISSUE TITLE
Can't change width of extant counter

### ISSUE THREAD

**Issue by edstott** [tomcl/issie#225]
**Describe the bug**
The width of a counter component cannot be changed if it is already on the sheet and either or both of the optional inputs are not activated.

**To Reproduce**
1. Place a counter component on a sheet
2. Select the component and switch to the Properties tab
3. Deselect an optional input 'Load' or 'Enable'
4. Change the value of 'Number of bits'
5. The width displayed on the sheet does not change and if the tab is changed or the component deselected the width reverts to its previous value

**Expected behavior**
The width should change even if one or more optional inputs are not activated

**Desktop (please complete the following information):**
- OS: Windows 10
- Version 3.0.0 built from https://github.com/tomcl/issie/commit/a83cc21920e497ee8b5c7527d268383ce3ed9827

**Comment by apantelopoulos** [comment]
Fixed on #232
