### ISSUE TITLE
Add 'OK' button to 'Select Waves' Dialogue

### ISSUE THREAD

**Issue by edstott** [tomcl/issie#226]
**Is your feature request related to a problem? Please describe.**
When setting up a Wave Simulation you need to choose the waves to display in a dialogue box. When you have finished, you must click the 'x' button to return to the main screen, which feels like a cancel action, rather than proceed.

![image](https://user-images.githubusercontent.com/4660308/190598229-3d8b40bb-7a71-4a7c-94e4-b9e789c84b54.png)

**Describe the solution you'd like**
The box should have OK and Cancel buttons

**Comment by tomcl** [comment]
Yes, I guess that would be clearer. It is conceptually correct because it is cancelling the wave selection box - but confusing

**Comment by tomcl** [comment]
Compromise: box now has Done button.

https://github.com/tomcl/issie/commit/fa944236ecc9c0a02ff21a79b97f428febd5c7b2

To implement fully needs a bit more work: delaying all changes till the end (which would be mildly desirable anyway so that waveform creation is all done together).

**Comment by edstott** [comment]
I think Done is fine. Thanks!

**Comment by tomcl** [comment]
Great!. Closing.
