### ISSUE TITLE
Insert components via drag & drop.

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#23]
<a href="https://github.com/ms8817"><img src="https://avatars2.githubusercontent.com/u/61198467?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ms8817](https://github.com/ms8817)**
_Wednesday Jun 24, 2020 at 15:49 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/64_

----

This should help: https://www.w3schools.com/tags/att_global_draggable.asp
Also, [Brainbox](https://github.com/freegroup/brainbox) uses the same drawing library and supports drag and drop, so peeking at how they do it may be helpful.

**Comment by MarcoSelvatici** [comment]
<a href="https://github.com/tomcl"><img src="https://avatars0.githubusercontent.com/u/7545073?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tomcl](https://github.com/tomcl)**
_Wednesday Jun 24, 2020 at 19:24 GMT_

----

As an interesting alternative, might consider insert components via intelligent heuristic placement!

**Comment by tomcl** [comment]
With nice component placement now I'm not sure that drag and drop is any better than what we have! Closing
