### ISSUE TITLE
Wave selections in Wave Simulation disappear on design change

### ISSUE THREAD

**Issue by edstott** [tomcl/issie#249]
**Describe the bug**
Wave Simulation allows you to refresh the waveform when you have changed the design. However, this usually causes some or all of the displayed waveforms to be deselected, even if they are for signals that were unaffected by the change.

**To Reproduce**
1. Make a sequential design with an output. Simulate it in Waveform simulator with all signals selected for display
2. Add another output
3. Click the green arrow refresh button in Waveform simulator
4. Some or all of the waveforms will disappear

**Expected behavior**
Waveforms should persist if the signals they display still exist in the design. It would be helpful if they persisted even if simulation is switched to a different sheet and back again, and if Issie is closed and reloaded. Students will probably use waveform simulator in their demos and that would work better if simulations can be prepared in advanced and the design can be altered without needing to reselect waveforms.

**Desktop (please complete the following information):**
- OS: Windows 10
- Version 3.0.0 built from https://github.com/tomcl/issie/commit/ff22773cda6fa56387e90e94b50e4a9871fc57a6

**Comment by tomcl** [comment]
closed by v3.0.2beta1
