### ISSUE TITLE
32-bit constants always return zero?

### ISSUE THREAD

**Issue by edstott** [tomcl/issie#256]
**Describe the bug**
A 32-bit constant seems to always resolve as zero in simulations

**To Reproduce**
1. Place a constant and an output, both 32 bits wide
2. Set the constant value to non-zero
3. Run Step or Truth Table simulations
4. The output is zero

**Expected behavior**
32-bit, non-zero constants should be possible

**Screenshots**

![image](https://user-images.githubusercontent.com/4660308/200019191-76c30774-bd50-4a27-a4a2-feacaad5d54e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - v3.0.2

**Additional context**
I have not tried every width up to 64, but I have tried a few and not found another width that does not work

**Comment by edstott** [comment]
32-bit bus selects also seem to be affected
Possible workaround is to use 2x16-bit constants or bus selects and a mergewires. Mergewires seem ok.

**Comment by tomcl** [comment]
closed by release https://github.com/tomcl/issie/tree/v3.0.3

**Comment by edstott** [comment]
Now it seems broken for any width!

![image](https://user-images.githubusercontent.com/4660308/200546226-3eae1676-6eef-41a5-b4e4-7a8de3c1cc0b.png)

I'm also seeing a problem if I try with splitwire instead:

![image](https://user-images.githubusercontent.com/4660308/200546744-43dc39c0-49c4-4db9-b1d2-10c841a8fa17.png)

v3.0.4 experimental
