### ISSUE TITLE
Step simulation output not changing

### ISSUE THREAD

**Issue by ccrownhill** [tomcl/issie#323]
**Describe the bug**
I found the problem with this circuit which should output 1 in this simulation setting but Y stays 0:

![image](https://github.com/tomcl/issie/assets/56307024/1471bbd8-50d5-4b2e-98d7-43018b930ea5)

Then I tested all gates by themselves which didn't work either:

![image](https://github.com/tomcl/issie/assets/56307024/a6503b06-6369-40e8-b587-76b4c0244d9c)

It didn't work for any other gates either. Note that for NOT, NAND and NOR it was constantly HIGH.

**Issie version**
This problem only happened with the current master branch version (commit: d940113) and not when I used the 4.0.1 version.

**OS:** Linux Mint 21

**Comment by tomcl** [comment]
This is a bug introduced from the new simulation. We thought it was fixed - but obviously not. It works now for clocked outputs but not combinational as here. (I tested - even combinational outputs in a circuit with clockjed outputs which is clocked never change from 0.

@0x6770  may be able to see quickly what is wrong and fix it!

**Comment by 0x6770** [comment]
This error was due to a misuse of `FastRun.runCombinationalLogic` in `FastRun.changeInput` which was introduced in a fix last week.
