### ISSUE TITLE
Small easy improvement to waveform simulation UI

### ISSUE THREAD

**Issue by tomcl** [tomcl/issie#327]
**Is your feature request related to a problem? Please describe.**

Waveform simulation UI is unclear when sheet simulated is combinational

**Describe the solution you'd like**

1. (easiest solution). After attempting to start the waveform simulation on a combinational sheet the UI should not say "simulation started" with a long text beneath.
2. (Better solution). When the waveform simulation tab is open on a combinational sheet, before simulation button is pressed,  the start button is greyed out and the "combinational circuits can only be simulated using step simulator message is displayed (as it is now when an attempt is made to run the waveform sim). For similar functionality note how the step simulator does not show (or greys out? - i can't remember) the STEP button if the circuit is combinational.

**Describe alternatives you've considered**

**Additional context**

**Comment by tomcl** [comment]
I need more context to understand this?

**Comment by tomcl** [comment]
Ah, yes.

I think:


  *   Delete "sheet" from title to simplify it
  *   Remove (i)
  *   Delete all text
  *   Add RH context menu item for help to title & text below
  *   If there are no waveforms and clocked logic change the message after starting simulation to "Use Select Waves to add waveforms. Right-click for help."
  *   Remove select RAM and negotiate with Samuel re adding it to the waveform selector.
  *   Swap the simulation & refresh buttons - remove refresh button (don't just inactivate it) if circuit has not changed.
  *   Add right-click help to all of cursor control explaining it.


What do you think?

**Comment by IlanIwumbwe** [comment]
That sounds good

**Comment by IlanIwumbwe** [comment]
Good evening Dr Clarke. I've been trying to add new context menus for help on the waveform simulator, but I'm not sure why I can't get it to work.
I added my context menu here:
![image](https://github.com/tomcl/issie/assets/56346800/ce8948a8-3068-41fb-9cee-5c7c9e67f08d)

But it isn't part of the context menus since I get this error: 
![image](https://github.com/tomcl/issie/assets/56346800/6fc7a4e3-f532-432c-a970-66a373889110)

Is there anything I am missing that can help?

Thank you

**Comment by tomcl** [comment]
You need to add a menu attachment to UpdateHelpers.getContextMenu  – which examines mouse posn and works out which menu.

type RightClickElement can be added to.

**Comment by IlanIwumbwe** [comment]
I had already done that. 
I added 'WaveSimHelp' to the DU:
![image](https://github.com/tomcl/issie/assets/56346800/31c3fe0e-7053-4040-b57e-a1c8dd8ab2d9)

Then added the attachment :
![image](https://github.com/tomcl/issie/assets/56346800/d9407ec4-a5c8-4093-a4ad-35dffc5b66ea)

Then added it under this match statement

**Comment by IlanIwumbwe** [comment]
Good morning, Dr Clarke. I rebuild Issie dev and the context menu shows up now.

What do you think about adding tabs for each feature under 'Waveform simulation' which have all the explanation about how it works, then maybe saying somewhere: 'Right click on element to navigate to help tab.' Then the tabs could be: 'Waveform and RAM selection, Waveform Operations, Cursor, Miscelleneous. 

![image](https://github.com/tomcl/issie/assets/56346800/e9029e8e-91b0-41f8-bf88-e0d302bd51f8)

**Comment by tomcl** [comment]
Looks good to me, I think. Are you happy with it?

Oh – check what it looks like if simulating a combinational ckt.

**Comment by IlanIwumbwe** [comment]
Yes, I'm happy with it. 

On a combinational circuit:
![image](https://github.com/tomcl/issie/assets/56346800/9d924bf2-9898-4421-91dd-f1d531cf08df)

**Comment by tomcl** [comment]
Yes – that is fine.

So what are you doing next?

**Comment by tomcl** [comment]
😊 understood! You have done a lot of work for issie!

**Comment by IlanIwumbwe** [comment]
Thank you very much! I've had a lot of fun working on it. I've also learnt a lot. 🙂

**Comment by tomcl** [comment]
clodsed with #413
