### ISSUE TITLE
Add a refresh button to Step simulation

### ISSUE THREAD

**Issue by tomcl** [tomcl/issie#337]
In the case that:
- The step simulation is running
- The  circuit has been changed from simulation start

Add a refresh button as on wav simulation

Colour refresh button according to whether there are simulation errors (like we colour start simulation button).

To reduce noise the refresh button should only appear when it is needed.
Simulation should stay on same Tick when refreshed.

**Comment by lucasng32** [comment]
May I be assigned to this issue?

**Comment by tomcl** [comment]
closed with #386
