### ISSUE TITLE
Breadcrumbs sheet select edge case

### ISSUE THREAD

**Issue by IlanIwumbwe** [tomcl/issie#387]
**Describe the bug**
If the user manually deletes files from a project directory then loads the project into Issie, there is an issue.
Dependencies that may have been deleted show up on the hierarchy tree, but when the user clicks them, Issie sometimes does nothing, and other times stalls with blue rotating wheel 

**To Reproduce**
1. Go to a project directory
2. Manually delete a file that is a dependency of another file
3. Go to 'Sheets'
4. In the hierarchy, click on the sheet you deleted 
5. See error

**Expected behavior**
Error message telling user what the problem is

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version v3.0.11

**Additional context**

**Comment by tomcl** [comment]
Fixed with #388 

NB - manually deleting sheets will mean references to them in otehr sheets don't work. I am not usre if this breaks issie in any bad way - I'd hope not.
