### ISSUE TITLE
Wrong top bar alignment

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#39]
![image](https://user-images.githubusercontent.com/26204867/91458574-f829ba00-e885-11ea-88f2-344b669dcad7.png)

As you can see in the screenshot, the tob menu bar and the canvas overlap. I am convinced that this is due to the the misconfiguration of:
https://github.com/tomcl/issie/blob/1c154ce3cfebfa96ee8979432691500e5c7f956c/src/Renderer/UI/Style.fs#L7
it should be 72 pixels instead.

**Comment by tomcl** [comment]
Thx. fixed
