### ISSUE TITLE
Code signing and notarisation is not working as expect

### ISSUE THREAD

**Issue by 0x6770** [tomcl/issie#396]
**Describe the bug**
The binary generated by `npm run dist` cannot be opened when download from GitHub release.

<img width="372" alt="Screenshot 2023-09-08 at 17 00 32" src="https://github.com/tomcl/issie/assets/34958528/2ce6df68-b37b-423c-bb80-0103ec072c2e">

This is due to error on code signing and notarisation. 
1. `scripts/afterSignHook.js` expects wrong `appPath` for code signing. Naming format of Mac binary is changed.
2. `provisioningProfile: "embedded.provisionprofile"` is not found in the root directory.

**Comment by tomcl** [comment]
:) Glad you have self-assigned!

**Comment by 0x6770** [comment]
Quick updates:

I'm still looking for a free way to code sign macOS app. It appears that membership of [Apple Developer Program](https://developer.apple.com/programs) is required to generate certificate and provisioning profile that are needed for code signing. (78 GBP for individual developer, free for nonprofit organization or educational institution, https://developer.apple.com/support/membership-fee-waiver/)

A safer temporary workaround is found that has no prerequisites and does not affect other apps. The `app is damaged` error #329 can be resolved by running

```
sudo xattr -rd com.apple.quarantine /Applications/issie.app
```

The installation path to issie may differ.

**Comment by tomcl** [comment]
I am closing this now since Yujie's workaround seems to work and is in README.
