### ISSUE TITLE
Copied component is pasted with ('cmd' + anything/nothing) 

### ISSUE THREAD

**Issue by theogam02** [tomcl/issie#397]
**Describe the bug**
While working on the eep1 project, I copied components from one sheet to another. I pasted the components on the new sheet. After that I tried using some shortcuts to rotate the component. The moment I pressed 'cmd' (or control for windows), the component was pasted twice more. This seems to keep on going for quite a while. It is when I pressed 'cmd' + 'c' again to clear the clipboard that it stopped. Can someone try this on their computer (windows as well) and see if this happens. I am sure someone would have noticed by now if this happened to them but it seemed pretty weird to me. Perhaps it came with one of the latest commits?

**To Reproduce**
1. Use eep1 project
2. Copy component from Datapath to new sheet
3. Paste component
4. Try using other shourtcuts with ctrl/cmd (windows/mac)

**Expected behavior**
The component should only be pasted once, with the correct shortcut

**Desktop (please complete the following information):**
 - OS: MacOs
 - Version 13.2

**Comment by tomcl** [comment]
It does not happen under windows - all is good.

You can trace all and then work out which messages the Cmd key press generates. on windows ctrl is used for additional functionality on custom components so we detect it - but it doe snot do anything else and is not confused with Ctrl + c.

**Comment by tomcl** [comment]
So the question is WHY is the keyup not detected. You can trace it through:
Message
Key down list.
Logic on that (maybe affected by sequence etc).
