### ISSUE TITLE
WaveSim not automatically calculating new values

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#40]
When opening the waveSim, you get the waveform for a certain number N of clock cycles. If then you try to inspect the waveforms at clock cycles M > N, the simulator does not provide accurate results, as you can see in the picture (N == 12).

![image](https://user-images.githubusercontent.com/26204867/91459960-8fdbd800-e887-11ea-8f72-b9c41f49ac0c.png)

This may be confusing to a first time user.

**Comment by tomcl** [comment]
This has now been fixed (some time ago) v.10.1+ releases are fine.
