### ISSUE TITLE
Error in terminal when executing the app with `yarn start`

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#41]
Running the application from the terminal using `yarn start` yields a series of errors like:

![image](https://user-images.githubusercontent.com/26204867/91461772-b00c9680-e889-11ea-886f-a958b851e21b.png)

Steps to reproduce:
- run `yarn start`
- the code should compile successfully and the application should start
- the errors should appear in the terminal, though not affecting the behaviour of the app (at least, none that I noted).

System:
Linux Ubuntu 20.04

Notes:
seems a low priority issue as it does not actually affect the behaviour of the app and may not even affect production releases.

**Comment by tomcl** [comment]
Yes, yarn start is the wrong command, it should be yarn dev - need to clean up the build scripts deleting ones that don't work.
