### ISSUE TITLE
v4.1.0 bug on macos importing sheets

### ISSUE THREAD

**Issue by Ivy-yu7** [tomcl/issie#430]
**Describe the bug**
Using ISSIE software on my MacBook. The problem lies in the inability to import sheets from one project to another.

 
**To Reproduce**
1. Go to any project. 
2. Click on top left Sheets - Import Sheet
3. Every sheet is grey (unable to be clicked on hence imported)

**Expected behavior**
Expect to be able to import sheets. 

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Monterey Version 12.3.1 (MacBook Air M1, 2020) Chip: Apple M1
 - I am using the latest version of ISSIE (v4.1.0)

**Additional context**
<img width="640" alt="Screen Shot 2023-11-25 at 03 57 42" src="https://github.com/tomcl/issie/assets/122407172/58ee1b8d-9e68-4e0f-a529-d4bad99b7c0e">

**Comment by tomcl** [comment]
I think this is a misunderstanding of the import function.

To use it:

1. Open the project you wish to add a sheet to
2. Click import sheet from the sheets menu
3. Select the project directory, and sheet9s0 within the directory, that you wish to import
4. Follow any confirmation dialogs

**Comment by tomcl** [comment]
This was in fact a bug in v4.1.0. Fixed now v4.1.1.
