### ISSUE TITLE
Demos not found on Macos

### ISSUE THREAD

**Issue by tomcl** [tomcl/issie#432]
**Describe the bug**
The demo projects are missing from macos builds

**To Reproduce**
1. Start Issie on arm64 macos
2. Click on demos
w. See "directory does not exist"

**Expected behavior**
teh lits of demos as on windows should appear.

 - OS: arm64 macos
 - Version v4.1.2

**Additional context**
This bug will be a macos/windows path issue. It is not obvious what it is looking at the code, but debugging on a Macos build should allow correction quickly.
Master has now debug printout that prints to console any paths that fail - that should be enough to debug if build on Macos.

**Comment by samuelpswang** [comment]
Fixed with #444.
