### ISSUE TITLE
Sheet changes lost when importing sheet

### ISSUE THREAD

**Issue by edstott** [tomcl/issie#433]
**Describe the bug**
Unsaved changes to an open sheet are lost when a sheet is imported to the project

**To Reproduce**
1. Create a new project. Place a component in the main sheet. Save the sheet
2. Add another component to the sheet
3. Import a sheet from a different project
4. The main sheet reverts to the saved version and the second component is lost

**Expected behavior**
Either:
1) The open sheet is unchanged when a sheet is imported; or
2) The user is prompted to save the open sheet when a sheet is imported

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version v4.1.2

**Comment by tomcl** [comment]
closed by #438 in v4.1.3
