### ISSUE TITLE
Refactor Waveform Simulator Layout with CSS Flexboxes

### ISSUE THREAD

**Issue by samuelpswang** [tomcl/issie#457]
**Describe the Bug**

1. Bad positioning of elements above wave window.
2. Waveform simulator window does not fill the whole of the right panel, with a constant 21px gap observed.
    * Scrollbar width is based on simulator window width.
    * Arbitrarily increasing the width of the window will mess up zoom and cursor button functions.

**Screenshots**

<img width="500" alt="wavesim-screenshot" src="https://github.com/user-attachments/assets/30e056b4-0602-48f3-9e11-5d8c9a70a0b7"><br/>

**Additional Context**

Providing additional detail to the discussion with @tomcl regarding the improvement of the Waveform Simulator layout.

**Comment by tomcl** [comment]
This is now closed by #464
