### ISSUE TITLE
Multi-page Truth Table Navigation

### ISSUE THREAD

**Issue by samuelpswang** [tomcl/issie#484]
**Is your feature request related to a problem? Please describe.**
The Truth Table feature under the Simulation tab does not have an intuitive way of seeing all rows of the displayed truth table. Students reportedly asked questions on how to see all rows.

**Describe the solution you'd like**
A scrollbar, either in HTML or via SVG canvas, would greatly help.

**Describe alternatives you've considered**
Current alternative is to use up-down buttons, which is not obvious to students.

**Comment by tomcl** [comment]
Truth tables are sort of an optional add-on for Issie. But I guess they now need some TLC. This is noted for possible dev in the Summer (sorry everyone this year). Thanks.

Re seeing all rows: partial solution: use Ctrl-Shift -  to zoom out.

**Comment by samuelpswang** [comment]
See discussion in #486, fixed in #490 (v5.2.2).
