### ISSUE TITLE
Ignore simulation outptus.

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#5]
<a href="https://github.com/ms8817"><img src="https://avatars2.githubusercontent.com/u/61198467?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ms8817](https://github.com/ms8817)**
_Friday Jun 19, 2020 at 13:29 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/36_

----

In some cases, you dont want to have certain wires in the simulation output. For example the ignore wire outside the program counter (it is the Cout of the four bit program counter adder).
![CPU](https://user-images.githubusercontent.com/61198467/85137453-8d368400-b241-11ea-9829-bec5b7a514f5.PNG)

**Comment by tomcl** [comment]
Labels, added, will allow this - add a label (which is not an output) and the wire is ignored.
