### ISSUE TITLE
Waveform view does not update when radix is changed

### ISSUE THREAD

**Issue by pclemow** [tomcl/issie#59]
When changing the radix in WaveSim, only the label at the right of the waveforms updates. The labels in each waveform segment remain as before 

![Waveforms_Hex](https://user-images.githubusercontent.com/73438136/97113668-cf863b00-16e3-11eb-8d6b-bcfc403989a5.png)
![Waveforms_Bin](https://user-images.githubusercontent.com/73438136/97113667-ceeda480-16e3-11eb-8126-8a10e8cbfebd.png)

**Comment by tomcl** [comment]
fixed 1.0.4
