### ISSUE TITLE
Start wavesim with initial input values

### ISSUE THREAD

**Issue by Jpnock** [tomcl/issie#66]
### What?

Add a "start wavesim with these initial values" button on the step simulation window, in order to enable the user to start the waveform simulation with user-specified initial values for inputs rather than zeros.

### When?

It should only appear on step 0 of a clocked design.

### Why?

A few times I've found myself swapping inputs for constants to replicate this functionality, then having to revert the change afterward.

Certainly not high priority at all but potentially a nice feature to eventually have.

Special thanks to @tomcl for your input on this feature request.

**Comment by tomcl** [comment]
I've changed tags on this because although doing this badly would be easy, doing it with a proper UI is not so straightforward. In addition, the top-level simulation UI is a bit of a mess at the moment so this should get folded into wider simulation overhaul.

**Comment by tomcl** [comment]
#160 would partially solve this issue.
