### ISSUE TITLE
Add a library of common hierarchical components.

### ISSUE THREAD

**Issue by MarcoSelvatici** [tomcl/issie#8]
<a href="https://github.com/ms8817"><img src="https://avatars2.githubusercontent.com/u/61198467?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ms8817](https://github.com/ms8817)**
_Friday Jun 19, 2020 at 13:51 GMT_
_Originally opened as https://github.com/MarcoSelvatici/DEflow/issues/40_

----

Basically, create a project and design a series of  common electronics components.

In order to use such library of components, it is necessary to place them in a known path, such as `~/.DEflow/lib/`, and tell the application to load those together with the other files in the project.

**Comment by tomcl** [comment]
folded into #147 - which is needed to do this nicely.
