### ISSUE TITLE
Negative circle radius when rendering segments

### ISSUE THREAD

**Issue by Jpnock** [tomcl/issie#89]
## Lines Affected

https://github.com/tomcl/issie/blob/a639848856dbc414013e82ab79d696827628cde0/src/Renderer/Draw2dWrapper/BusWire.fs#L297-L300

## Summary

If `width = "1"` then `renderWidth = 1.5`, hence `halfWidth = -0.25` which is then set as the circle radius.

This causes a console error to be logged and breaks copy/paste functionality.

**Comment by JEMerrick** [comment]
Yep sorted, I will update to version 1.9.3 with this bugfix on the release page, thanks for letting me know
