### ISSUE TITLE
Components naming

### ISSUE THREAD

**Issue by vaclavpavlicek** [tomcl/issie#97]
When I add a new constant to the sheet the number in the name of the constant is not incremented and therefore it causes an error because the sheet contains 2 components with the same name. I think it would be better if the number in the constant name would increment automatically. The same issue applies to bus select components.

![sels_bug](https://user-images.githubusercontent.com/6002134/117847077-523aa600-b282-11eb-9253-067f9e7be59f.png)

https://user-images.githubusercontent.com/6002134/117846977-3a632200-b282-11eb-8e67-6c9eda387bfe.mp4

**Comment by JEMerrick** [comment]
Thanks for letting me know! I've just sorted this and it should be available in the newest ISSIE (we are due to release 2.0.0 today)
